### ISSUE TITLE
Page crash and loss of work

### ISSUE THREAD

**Issue by zombiesbyte** [apigitlabs/apigit-support#1]
After spending 40 mintues writing up some routes I clicked a button and crashed the app.

1. Steps to reproduce:
1. Create a new path
1. Create a Post path
1. Go to the body section and click +contents
1. Select application/json
1.Click +example (I clicked it to see what it was)

Error page shows and all changes lost

![image](https://user-images.githubusercontent.com/19256347/208445755-e3a0d260-110d-41c5-90a1-8f60d83ee47a.png)
![image](https://user-images.githubusercontent.com/19256347/208445784-972d5920-f5a2-4d93-8e9f-84ab207874fb.png)

**Comment by apigitlabs** [comment]
thanks @zombiesbyte  for report this issue, we are very sorry about it. the crash was caused by an underlying UI library upgrade.
We just fixed it, please let us know if there is any further problems.

**Comment by apigitlabs** [comment]
problem fixed and live now
