### ISSUE TITLE
Mark properties as required

### ISSUE THREAD

**Issue by jhordies** [apigitlabs/apigit-support#11]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

There is currently no way in the form editor to specify if a property is mandatory or optional.

### Describe the solution you'd like

I would like to be able to set for each property if it is required or optional

### Describe alternatives you've considered

Manually edit the code

### Additional context

Required Properties
By default, all object properties are optional. You can specify the required properties in the required list:
type: object
properties:
  id:
    type: integer
  username:
    type: string
  name:
    type: string
required:
  - id
  - username
Note that required is an object-level attribute, not a property attribute:
type: object
properties:
  id:
    type: integer
    required: true  # Wrong!
required:           # Correct
  - id
An empty list required: [] is not valid. If all properties are optional, do not specify the required keyword.

**Comment by jimwu1518** [comment]
hi @jhordies , we have a "checkbox" to mark the property is required or not. It was already supported, can you help to double check it is your desired solution ?
![Screenshot from 2023-02-19 11-46-31](https://user-images.githubusercontent.com/119365251/219971490-101cae8e-946f-498f-a6a6-158cb629c1cb.png)

**Comment by apigitlabs** [comment]
hi @jhordies, we have the "checkbox" to select which property is "required" or not. please help to double check it is what you are looking for ?

**Comment by jhordies** [comment]
Hello, thanks for your reply.
I didn't understand what it meant, so checked means required?

**Comment by apigitlabs** [comment]
Yes, checked it means it is required. You can see the changes in diff view
 view after you checked.

We will add some tooltips to improve the user experience.

Thanks,
apigit

**Comment by jhordies** [comment]
Actually, this checkbox is only there for URL parameters not for schema payload

**Comment by apigitlabs** [comment]
hi @jhordies , it is also supported in schema. attached is the screenshots of an schema object definition. there is a checkbox there .
![Screenshot from 2023-04-15 10-32-06](https://user-images.githubusercontent.com/113477168/232244221-0963ccfc-8f25-404f-86a1-7ebec5b35f1b.png)

**Comment by jhordies** [comment]
Thanks, you can close the issue.
