### ISSUE TITLE
Update the schema references when renaming a schema

### ISSUE THREAD

**Issue by jhordies** [apigitlabs/apigit-support#12]
Currently if one renames a schema, all references are broken.
Please update the references.

**Comment by apigitlabs** [comment]
Thanks Jérôme, we will do an improvement for it soon

Apigit

**Comment by jhordies** [comment]
Thanks, I appreciate. I would love to have this implemented because everytime I rename a schema, I have to manually copy all the code, go to another website to find the wrong references, then fix in the code. It really breaks the spec file.

**Comment by apigitlabs** [comment]
thanks @jhordies , we will have a deployment scheduled at this weekend. it will includes an improvement to it.

**Comment by apigitlabs** [comment]
@jhordies , "update schema reference when renaming a schema" was supported now. Please check if it works as you expected.

**Comment by jhordies** [comment]
Thanks, It works ! This will save me a lot of time. (BTW, thanks to your support, I ordered licenses)

**Comment by apigitlabs** [comment]
thanks @jhordies for your support and order.
