### ISSUE TITLE
Reorder parameters or schema items

### ISSUE THREAD

**Issue by jhordies** [apigitlabs/apigit-support#13]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

When I need to reorder parameters or schema items, i have to manually change the code.

### Describe the solution you'd like

I would like to be able to graphically rearrange them by drag and dropping the line or press an up/down button

### Describe alternatives you've considered

To graphically rearrange them by pressing an up/down button

**Comment by apigitlabs** [comment]
hi @jhordies , we've recently implemented drag-and-drop functionality for reordering parameters. Please take a look and let us know if this meets your needs.

Regarding the possibility of reordering fields in the Schema, we are currently evaluating whether or not to support this feature. It's worth noting that the order of fields in an object is not always guaranteed, so we want to ensure that any implementation is both reliable and useful.  if you have any guidance on this, please let us know.

**Comment by jonathanwyckmans** [comment]
hi, I've created a similar feature request : https://github.com/apigitlabs/apigit-support/issues/28 which I will delete. 
The drag & drop functionnality is not working on my end. COuld you confirm if was implemented ?

**Comment by apigitlabs** [comment]
hi @jhordies , the feature was supported, please double check. we close the ticket first.
