### ISSUE TITLE
Renaming of a tag doesn't update it's references

### ISSUE THREAD

**Issue by jhordies** [apigitlabs/apigit-support#16]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Assume that a tag was used, if one renames it, the references are broken.

### Steps To Reproduce

Create a tag "A"
Use the tag for an endpoint
Rename tag "A" to "B"
--> invalid json as the endpoint still refers to tag "A" that doesn't exist

### Browser

Chrome

**Comment by apigitlabs** [comment]
this is known issue for a while, we just fixed it, please check if it works for you.

**Comment by jhordies** [comment]
Thanks, it works now, you can close the issue
