### ISSUE TITLE
Inability to select an API spec when generating mock server script

### ISSUE THREAD

**Issue by neildobson-au** [apigitlabs/apigit-support#17]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When I go to mock server scripts tab and click automatic mock server script generation link, I have no ability to select an api spec

![image](https://user-images.githubusercontent.com/6670753/235391726-0426f4c5-e47e-4e64-ace3-93444879f985.png)

And so generation fails

![image](https://user-images.githubusercontent.com/6670753/235391890-589a9115-8af0-41b0-bced-f8d450eece4c.png)

I have a single valid spec

![image](https://user-images.githubusercontent.com/6670753/235391791-97537fc3-3730-4a9c-b198-3ea76f8e02dc.png)

### Steps To Reproduce

1. Delete all examples
2. Create an open api spec in `.apigit\code\spec.yaml`
3. Go to mock server scripts tab
4. Click automatic mock server script generation link
5. Observe inability to select an api spec and error generating script

### Browser

Brave

**Comment by apigitlabs** [comment]
hi @neildobson-au , based on your screenshots, i see you put your API spec under .apigit folder, this folder is reserved for apigit automation purpose. so when you generate mock server scripts, it will not count files under this folder. please create a new spec other than in ".apigit" folder, then you can copy your existing spec to that spec and do mock server generation.

**Comment by neildobson-au** [comment]
Thank you. I copied the spec to repo root and indeed that spec is available for selection in the generator dialog.
