### ISSUE TITLE
Allow editing example in schema form

### ISSUE THREAD

**Issue by neildobson-au** [apigitlabs/apigit-support#18]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

When defining schema you can create a property-level example:

```json
{
  "properties": {
    "clientReference": {
      "type": "string",
      "description": "Client-provided identifier",
      "example": "ef9bd8e5-5781-4ed9-80ef-39a0b5bd41ce"
    },
    "name": {
      "type": "string",
      "description": "A descriptive name for display purposes",
      "example": "Smith, 52 George St"
    }
}
```

But seems there's no way to edit the example without going into code view.

Also there's a schema example button which renders a json object from the schema. But each field does not use the example value and so you end up with:

```json
{
  "clientReference": "string",
  "name": "string"
}
```

instead of

```json
{
  "clientReference": "ef9bd8e5-5781-4ed9-80ef-39a0b5bd41ce",
  "name": "Smith, 52 George St"
}
```

### Describe the solution you'd like

1. Allow editing the example value in the same row as the description

![image](https://user-images.githubusercontent.com/6670753/235413492-c34de32d-1d99-4a32-ad8f-b2c87db7b840.png)

or in the advanced setting dialog

![image](https://user-images.githubusercontent.com/6670753/235413582-62d60b30-5e5f-4632-9fba-f19188e79fb6.png)

2. Take the example value if given, or fall back to default value if given, when creating a readonly example 

![image](https://user-images.githubusercontent.com/6670753/235413808-c539bcdf-a8e4-428d-8979-302985adab34.png)

**Comment by apigitlabs** [comment]
thank you,  @neildobson-au , they are very nice suggestions. 
regarding #1, which is already supported  in the advanced setting dialog. It is already showed up in your screenshots. 
regarding #2, our R&D team has just deployed a version to improve it today, please check if it works for you now.

**Comment by neildobson-au** [comment]
Thank you for the prompt response. As per point 2, example is now working
![image](https://user-images.githubusercontent.com/6670753/235551677-31d8f36a-bd7b-48bd-ac42-a60dd3dba208.png)

And for point 1, I didn't spot this before. You can indeed edit the json schema directly in the advanced dialog. I wonder if a few users might mistake this for a read-only view.

Anyway, thanks this solves my issues. Great product btw :+1: . I did spot some typos so I'll raise separate tickets.

Thanks.

**Comment by apigitlabs** [comment]
thanks @neildobson-au, we will close this ticket first. feel free to open new tickets if you find anything else in future.
