### ISSUE TITLE
UX issue when using $ref in Request definition

### ISSUE THREAD

**Issue by nad-au** [apigitlabs/apigit-support#20]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

In the edit form when you define a **Request** you can edit Path Param, Query Param, Headers, Cookie and Body. When you create any of these items and select `$ref` as the type, it expands all sections and creates a placeholder `$ref` entry in each.

To be fair it does hide the other sections after creating an entry so not too much of a problem.

### Steps To Reproduce

1. Edit a spec
2. Edit a path
3. Go to Request section
4. Change type to $ref
5. Observe a placeholder row gets created for each Request type

### Browser

Brave

**Comment by apigitlabs** [comment]
Thanks, @neildobson-au. This is a known issue that occurs when a new $ref is added without specifying a target for it. As a result, it becomes unclear which target(query, path, header,cookie) the new parameters should belong to. We acknowledge this problem and plan to address it by implementing an improvement.

**Comment by apigitlabs** [comment]
problem was fixed
