### ISSUE TITLE
SSH not working

### ISSUE THREAD

**Issue by ChinaeduO** [apigitlabs/apigit-support#23]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When trying to access my mock server via HTTPS, it is not working. From Postman, I am getting a warning that something is going wrong with the certificates.

### Steps To Reproduce

1. Create a mock server
2. Try to request an endpoint through HTTPS with Postman

### Screenshots or Videos

<img width="356" alt="Bildschirmfoto 2023-06-06 um 22 03 20" src="https://github.com/apigitlabs/apigit-support/assets/107402400/206fe653-2974-45e8-ad15-6e038f6ed789">

### Browser

Postman

**Comment by apigitlabs** [comment]
hi @ChinaeduO , the problem is fixed. please double check if it works in your side now.
