### ISSUE TITLE
Include in form mode the possibility to specify anyOf, oneOf in $ref (Inheritance and Polymorphism)

### ISSUE THREAD

**Issue by fstapf** [apigitlabs/apigit-support#24]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

When needing to specify more than one reference, it can only be done through code.

### Describe the solution you'd like

API Specifications > spec files > edit > schema > add > advance settings
In the advanced settings window of the $ref object type, add a field to specify the Inheritance and Polymorphism type (using the oneOf or anyOf keywords). After selecting the type, allow the entry of more than one reference.

API Specifications > spec files > edit > schema > add
On the main screen, within the object, instead of displaying an empty dropdown, display $ref.

API Specifications > spec files > visual mode > swagger || default > examples
API Specifications > spec files > edit > schema > example
Construct an example with all possible types automatically.

### Additional context

When specifying an Inheritance and Polymorphism, both the swagger mode and the default mode recognize the type, correctly displaying it in the documentation. However, in the form editing mode, the dropdown remains blank when specifying an anyOf in advanced settings.

https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/

**Comment by apigitlabs** [comment]
hi @fstapf , thanks for reaching out. Our dev team is looking at this now, we will give you an update shortly.

**Comment by apigitlabs** [comment]
hi @fstapf , our dev team has made some improvements to support Inheritance and Polymorphism (oneOf/anyOf/allOf). Please help to check if this fits your needs.
