### ISSUE TITLE
Cannot use allOf in form view

### ISSUE THREAD

**Issue by fkfv** [apigitlabs/apigit-support#25]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When trying to use allOf for model composition (https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/) the form view is not working correctly.

If you try to select allOf in form view it will be converted to anyOf
If you try to manually add allOf using code view {"type": "string"} will be added to schema, but it will still display in documentation correctly after closing edit view.

### Steps To Reproduce

1. Open edit mode
2. Create new schema
3. Try to select allOf as type
4. It is changed to anyOf
5. 

1. Same schema, open advanced settings or code view
2. Enter an allOf keyword, example below
3. It is converted to a string type

```json
{
  "allOf": [
    {
      "type": "object",
      "properties": {
        "test1": {
          "type": "string"
        }
      }
    },
    {
      "type": "object",
      "properties": {
        "test2": {
          "type": "string"
        }
      }
    }
  ]
}
```

### Browser

Chrome 116

**Comment by apigitlabs** [comment]
thanks @fkfv for pointing out the problem, our QA team missed the issue. the bug was fixed and re-deployed online, please help to check if it works well for you at your convenience.

**Comment by apigitlabs** [comment]
the issue was fixed and close it
