### ISSUE TITLE
Getting "invilid file name" when trying to import large file

### ISSUE THREAD

**Issue by sambenas** [apigitlabs/apigit-support#26]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Uploading a large file, about 20MB, I get an "invilid file name" error.  It is valid OpenAPI and if I delete a bunch of endpoints I can upload it successfully.  Is there a maximum supported file size?  I didn't see one anywhere.

### Steps To Reproduce

1. Upload large OpenAPI spec file

### Browser

Chrome

**Comment by apigitlabs** [comment]
hi @sambenas , yes, there is a hard limitation of spec size, which is 10M. We have no plan to lift this limitation as if the spec size goes too big, the browser will become frozen when that too big spec. we recommend customers to split a long spec into multiple small spec, which is also benefit the customers for easier review.

**Comment by sambenas** [comment]
@apigitlabs Thank you for clarifying!
