### ISSUE TITLE
Ordering of Paths & Schema

### ISSUE THREAD

**Issue by jonathanwyckmans** [apigitlabs/apigit-support#28]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Currently the paths & schemas are static. If we want to order them, we need to copy existing endpoints in the order required and delete the old ones.

### Describe the solution you'd like

Being able to re-order the paths & schemas. I want to be able to set my list of endpoints in the order I desire. So that if I have multiple domains in my endpoints, I can order them chronologically (not only with tags)

**Comment by jonathanwyckmans** [comment]
Duplicate of https://github.com/apigitlabs/apigit-support/issues/13

**Comment by apigitlabs** [comment]
thanks @jonathanwyckmans , good request, we have put it in road map and will get it supported shortly.
