### ISSUE TITLE
Support to edit the components through UI forms

### ISSUE THREAD

**Issue by jvahldick** [apigitlabs/apigit-support#29]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Editing the API specification through UI is a great time-saver, and I believe this feature should also be expanded to the components. Nowadays, when editing a specification, there are a couple of options: _Info, Tags, Servers, Security, Paths, Webhooks, Schema, Parameter_

Ideally, it would be great if the client could define what components should be visible/edited through UI.

For example, responses, headers, and request bodies are beneficial, and it would be handy to edit through UI to not overload the "Schema" node.
https://swagger.io/docs/specification/components/#structure

### Describe the solution you'd like

**Option 1:**
IMO, that's the best option.

Having a section where the client can add/remove components and define their schema. That would be displayed as a standalone element in the menu when editing the schema through UI.

**Option 2:**
Have _some pre-defined_ components, as it is in Stoplight. In Stoplight, there is also a specific section to manage the components, and you can create folders, etc, to manage them more efficiently.

Please see the images:

<img width="397" alt="Screenshot 2024-02-23 at 12 48 25" src="https://github.com/apigitlabs/apigit-support/assets/1113015/cee33a36-7798-4b5e-bd18-552c7b926bf1">
<img width="333" alt="Screenshot 2024-02-23 at 13 12 34" src="https://github.com/apigitlabs/apigit-support/assets/1113015/e33ee047-7602-40d6-be92-46e3127f46be">

The image on the left is the APIGit, which has new components (in green) that the client could edit.
The image on the right side is the specific section of components. Then, when editing the schema through the form, we can refer it to some component node whenever we select an object.

**Comment by apigitlabs** [comment]
hi @jvahldick , we just get it supported to edit or reference components like requestBody, response, schema and parameters. please have a try and let us know if you have further questions.
