### ISSUE TITLE
Endpoint description replaces it's path in the menu 

### ISSUE THREAD

**Issue by jhordies** [apigitlabs/apigit-support#3]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When filling the description of an endpoint (I use markdown) the endpoint path in the menu gets replaced with the description.
In my case it looks ugly because its the unformatted markdown string.

### Steps To Reproduce

Set a markdown documentation in the description of an endpoint and save.
Then browse the open api.
The menu item to get to that endpoint is now messed up

### Browser

Chrome

**Comment by apigitlabs** [comment]
thanks @jhordies, the improvement has been added.
