### ISSUE TITLE
Typo - Terms of Sercie URL

### ISSUE THREAD

**Issue by ehcanadianCA** [apigitlabs/apigit-support#30]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

There is a typo for the Terms of Service URL. Info -> General section.

### Steps To Reproduce

See screenshot.

### Screenshots or Videos

![image](https://github.com/apigitlabs/apigit-support/assets/8474633/fe41605d-a4b4-4f5f-8b1c-6f376068a101)

### Browser

Chrome

**Comment by apigitlabs** [comment]
issue was fixed in the new deployment
