### ISSUE TITLE
Share components between specs

### ISSUE THREAD

**Issue by manuliner** [apigitlabs/apigit-support#31]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

I have several API References for many different microservices. They may use same components, like parameters, reponses etc.
duplication and keeping all up to date is much work

### Describe the solution you'd like

centralised components accessable via ref

### Describe alternatives you've considered

using another tooling

**Comment by apigitlabs** [comment]
Hi @manuliner, Apigit's API Editor supports a wide range of components (like parameters, headers, requests, responses, etc.) that can be referenced by all other objects as 'ref.' Could you explain more about the issue you encountered?

**Comment by manuliner** [comment]
I have several Microservices. For every single one i have an service-1-openapi.yaml

I want to keep all yamls in one repository.
Service 1 and Service to sharing the same responses, parameters, Models and so on.
Currently i store those in an folder (Common) and Link those specific files into the main yaml file to reduce duplication

Those common components yaml are not recognized bu apigit

**Comment by apigitlabs** [comment]
hi @manuliner , this function is gotten supported in the latest deployment, please have a try!
![apigit-openapi-split](https://github.com/apigitlabs/apigit-support/assets/113477168/49b235e9-c3c2-4a32-9f76-c016a6fa121a)

**Comment by manuliner** [comment]
nice.  That was fast. Awesome

Sadly your "Form View" is not accepting it as valid openAPI.yaml
![grafik](https://github.com/apigitlabs/apigit-support/assets/5088151/6f7c5c76-ada7-4367-ab70-2ec436e20470)


and it would be nice to have those shared components acessable in the edit view of the "main" spec file
![grafik](https://github.com/apigitlabs/apigit-support/assets/5088151/4bf2f9e1-2d16-4956-b9de-50d52c657e2b)

**Comment by apigitlabs** [comment]
Thank you, @manuliner. Regarding the externally shared components, these could be either a component in JSON schema style or just a regular JSON. This makes it somewhat tricky to manage. We will conduct some research to see if there's a feasible way to handle this.

**Comment by apigitlabs** [comment]
hi @manuliner , we have basically supported json schema spec viewer and editor. Please try it and let us know if you have any questions.
![json-schema-editor](https://github.com/user-attachments/assets/957f47b4-15c1-438f-9d84-8a45926d8e8f)
![json-schema-viewer](https://github.com/user-attachments/assets/560b62c4-e899-4a88-8090-b06b5ba12713)

**Comment by apigitlabs** [comment]
I close the issue first.  if you have any further request,please let us know.
