### ISSUE TITLE
Live Preview in Viewer

### ISSUE THREAD

**Issue by manuliner** [apigitlabs/apigit-support#33]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

no

### Describe the solution you'd like

![grafik](https://github.com/apigitlabs/apigit-support/assets/5088151/83444342-a807-4c0c-8e8f-6c4e52db5ef1)

Add "Viewer" to those option to get an preview without commiting changes

Splitview in the samte Browsertab or open in a new window which i can move to another monitor would be great

**Comment by apigitlabs** [comment]
![Screenshot from 2024-05-06 17-31-16](https://github.com/apigitlabs/apigit-support/assets/113477168/d4436528-f4b0-4edf-8121-709cecc67eed)

Hi @manuliner,

The team has just deployed a patch that includes a preview function in the API editing mode. However, we have not implemented this in a split window, as rendering an entire document while editing would significantly decrease performance and user experience. In our latest update, you can switch to the preview tab to view changes without exiting the editing mode. We hope this addresses your concerns. please refresh your browser and give it a try.
