### ISSUE TITLE
Add Path layout displaying weird

### ISSUE THREAD

**Issue by vuhieutopicus** [apigitlabs/apigit-support#35]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The List of tags in the Add Path screen and Edit Path screen display weird and hard-to-choose

### Steps To Reproduce

1. Open the Project
2. Go to edit mode
3. Create a new Path or update a Path
4. Layout displaying weird

### Screenshots or Videos

<img width="340" alt="image" src="https://github.com/user-attachments/assets/f77074af-7eac-42e1-afd3-538a4d34a537">

### Browser

Chrome

**Comment by apigitlabs** [comment]
thanks @vuhieutopicus for reporting the issue, the problem was just fixed. please refresh browser to try it again.
