### ISSUE TITLE
OpenAPI extensions should be included in the UI

### ISSUE THREAD

**Issue by Stwissel** [apigitlabs/apigit-support#36]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

We use `x-extensions` to configure our API, they are not visible in the edit form or the preview

### Describe the solution you'd like

OpenAPI allows extensions:
- 3.0.x https://spec.openapis.org/oas/v3.0.0.html#specification-extensions
- 3.1 https://spec.openapis.org/oas/v3.1.0.html#specification-extensions

When added to the OpenAPI source code, they are preserved, but they are not visible anywhere in form or preview which makes them hard to use. Has been solved in other GUIs:

<img width="2049" alt="Screenshot 2024-11-05 at 17 05 21" src="https://github.com/user-attachments/assets/6decf6b7-5b18-49a0-b126-e3f2fa071ad0">

P.S.: Love your work!

### Describe alternatives you've considered

Use apicur.io to cross check

**Comment by apigitlabs** [comment]
hi @Stwissel , 

Thank you for highlighting this requirement. We understand the need to support the OpenAPI x-extension. However, it was initially a lower priority for us as this extension is quite vendor-specific and can appear at various levels within the OpenAPI specification. Our code editor currently has the flexibility to support it in any configuration.

Could you share more about where exactly you plan to use the extension in your spec? For instance, is it at the root, path, operation, or schema level? If this is a common use case, we could prioritize implementing quick support for it ahead of a full extension rollout in the form editor.

**Comment by Stwissel** [comment]
We use `x-roles` on the method level to define the roles for RBAC. That's our current use. 
We used other `x-...` flags on the path level and inside info before. It is quite common (e.g https://www.npmjs.com/package/express-openapi-validator )

**Comment by apigitlabs** [comment]
thanks @Stwissel for the quick response and  valuable suggestion, we will take a look and let you know if there is any update.

**Comment by apigitlabs** [comment]
thanks @Stwissel , per your request, we have get it supported in spec info and spec method level. please refresh browser to take a look if it match your expect.

**Comment by Stwissel** [comment]
You people are awesome. Some finishing touches needed:

- doesn't show in the SwaggerUI
- doesn't show in ReDoc

I checked, current Swagger does display extensions, so it might just need a library update.
![image](https://github.com/user-attachments/assets/01616991-b487-428c-b912-fcf032f2f696)

ReDoc doesn't seem to show, so I would put that on low priority until upstream provides

**Comment by apigitlabs** [comment]
thanks @Stwissel , it is a configuration on Swagger ui, we have added it support. please refresh browser to have a try.

**Comment by Stwissel** [comment]
all good, you people are awesome
