### ISSUE TITLE
UI review - some ideas

### ISSUE THREAD

**Issue by Stwissel** [apigitlabs/apigit-support#38]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

First of all: you rock!

I used the Form UI on a 4K monitor and found myself scrolling up and down quite a bit.
A little vertical cleanup could improve that. I've compiled some ideas below

## Consistent add UI
Most of the add function use the (+) button -> I like it. However "Security", "Body content", "Responses" use the dropdown model. I would make the (+) the only add UI element

## Request Body not always needed, takes a lot of space
Add a (+) button like Parameters just above and don't display body stuff if not clicked (and you need a trash button then too) - or have 3 ( ): the two existing and () No Body

## Make description expendable
Just show one line and (...) with an expand button. Eventually memorize it. Btw. love the markdown editor, is it a component i could use?

## Consider to put single line labels in front of the input field
Give it a hard look, it might impact the aesthetics too much. There are a number of one liners where you could pull the label on the same line as the input field saving vertical space
- Path
- Description (consistency: makrdown input vs. one liner ?)
- Security

### Describe alternatives you've considered

Keep up the good work.

**Comment by apigitlabs** [comment]
Thanks, @Stwissel , for all the great suggestions. Your thoughtful guidance is much appreciated. We've implemented most of the improvements—please refresh browser and give them a try!

**Comment by Stwissel** [comment]
Awesome, like your updates
