### ISSUE TITLE
"requestBody": {} fails OpenAPI validation

### ISSUE THREAD

**Issue by Stwissel** [apigitlabs/apigit-support#39]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

An empty requestBody leads to a OpenAPI validation error:
[minimal-example.json](https://github.com/user-attachments/files/17743282/minimal-example.json)

here: https://oas-validation.com/

### Steps To Reproduce

1. create a simple get request (or use the attached file)
2. run the validation here: https://oas-validation.com/
3. it will fail
4. remove `"requestBody": {},`
5. validation succeeds

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/ae53755b-6fdf-475e-be6e-2b1f37645ce8)

### Browser

Firefox

**Comment by Stwissel** [comment]
also fails with Eclipse vert.x OpenAPIRouter

**Comment by apigitlabs** [comment]
thanks @Stwissel , it was fixed, please refresh browser to have a try

**Comment by Stwissel** [comment]
You rock
