### ISSUE TITLE
Keep Session open during edit

### ISSUE THREAD

**Issue by jhordies** [apigitlabs/apigit-support#4]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

The session is very short and edits can span over long periods of time. When you finally commit, the session is over, I need to login again and my work is lost

### Describe the solution you'd like

I don't want to lose my work, Keep the session alive, make it longer, save the changes locally but don't let a user loose his changes

**Comment by apigitlabs** [comment]
current session timeout is 1 hour, engineering team is investigating to see if there is any improvement needed. We will update later.

**Comment by apigitlabs** [comment]
Our engineer team has adjust the session timeout to 4 hours (from 1 hours).  Feel free to let us know if you have further questions. we appreciated all of your great suggestions.

**Comment by jhordies** [comment]
> Our engineer team has adjust the session timeout to 4 hours (from 1 hours). Feel free to let us know if you have further questions. we appreciated all of your great suggestions.

I appreciate your support and see a lot of potential in apigit.

IMHO, the re-login flow should avoid to leave the edit screen to avoid loosing the changes, 4 hours should be long enough but still when one spends a lot of time editing (and get interrupted), he should never loose his work.

**Comment by apigitlabs** [comment]
thanks @jhordies , our engineering team has added an automatic session refresh in editing mode, so you will never get logout while editing.

**Comment by jhordies** [comment]
Great news!
If I may, just bear in mind that the auto refresh of the session might not
work while the tab doesn't have the focus, I know chrome is very eager to
arvest resources and kills that kind of background task.

**Comment by apigitlabs** [comment]
Thank you, @jhordies , for your expert guidance. We greatly appreciate your help in finding a solution to improve the re-login flow. Although it may take some time, we are committed to implementing the changes you have recommended.

**Comment by neildobson-au** [comment]
Hi, I was about to raise a bug on this. I'm using Brave browser and I experienced the same today where I was working on some long edits. When I came to commit, it redirected to login and I've lost everything.

It would be good if session refresh could be checked across a range of popular browsers as this is key functionality. The browser session should just work without having to worry about when I last logged in or refreshed. Perhaps consider a banner or some other indicator if the app can detect the session is expiring or at least perform in-app refresh without requiring re-authenticating. 

Failing that, cache the local edits so they can be resurrected in a new session.

Thanks

**Comment by apigitlabs** [comment]
thanks @neildobson-au , do you remember how long  you have been worked on the editing and not commit ? we will find a way to improve it

**Comment by neildobson-au** [comment]
The typical scenario is that I open the app in view mode and read the API docs early in the day. I start working on implementing APIs so I'm not looking at browser window but using ide tools. I occasionally cross reference and when I need to change something I'll edit and commit. It could be long periods before I return to the browser.

One thing for sure is that the edit itself is not in the region of hours though. So it's likely the session was about to expire before I attempted to edit.

**Comment by apigitlabs** [comment]
thanks Neil, that what we thought.  We improved the logic before, if it is
in edit mode, we will do auto token refresh to make sure it will not
expired. But if it is in view mode, the session will be lost soon after
some idle hours. Anyway, we will see how to make further improvements to it.

Apigit
