### ISSUE TITLE
Typo: Qeury Param --> Query Param

### ISSUE THREAD

**Issue by jhordies** [apigitlabs/apigit-support#5]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

There is a typo in the openapi viewer : 
Qeury Param

### Steps To Reproduce

Open an open api spec and check an endpoint 

### Browser

Chrome

**Comment by apigitlabs** [comment]
thanks @jhordies , this typo was just fixed.
