### ISSUE TITLE
$ref not selected 

### ISSUE THREAD

**Issue by jhordies** [apigitlabs/apigit-support#6]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When importing an openapi spec with $ref to a schema in a query parameter, the drop down value of the type of parameter is empty. 

### Steps To Reproduce

import an openapi spec with $ref to a schema in a query parameter, see that the drop down value of the type of parameter is empty

### Browser

Chrome

**Comment by apigitlabs** [comment]
will investigate it.

**Comment by apigitlabs** [comment]
@jhordies ,  this is previously not supported, we just get it basically supported. please check if it already meets your need.
