### ISSUE TITLE
Collapse the left menu 

### ISSUE THREAD

**Issue by jhordies** [apigitlabs/apigit-support#7]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

On a 15" laptop screen it is hard to see all the fields and values in the editor because a fair amount of the screen is taken by the menu and there is no horizontal scroll bar.

### Describe the solution you'd like

 It would be nice to be able to collapse the left menu or at least be able to control it size. 

### Describe alternatives you've considered

A scroll bar

**Comment by apigitlabs** [comment]
thanks @jhordies , this is very valuable suggestions, our engineering team has added it supported.
