### ISSUE TITLE
Include a pointer where the error is when the spec is not readable by the form editor

### ISSUE THREAD

**Issue by jhordies** [apigitlabs/apigit-support#9]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I had to merge the open api spec with an updated version manually in the code editor.
I had to go to https://apitools.dev/swagger-parser/online/ to find what the problem was.

### Steps To Reproduce

Mess up the code of a spec.
Commit your changes.
Go to the form editor --> no usable anymore 

### Browser

Chrome

**Comment by apigitlabs** [comment]
thanks @jhordies, it is in our road map, but it may take a while to do it well. For better experience, team just added a quick improvement that when the API Spec can't be rendered in "form" viewer, then we automatically switch to "swagger-ui" viewer.

**Comment by jhordies** [comment]
Thanks!
